### ISSUE TITLE
Incorrect media sorting

### ISSUE THREAD

**Issue by mzygmunt** [typestyle/typestyle#68]
Hello,
consider following case:
http://typestyle.io/play/#src=const%20a%20=%20style(%0A%20%20%7Bcolor:%20%22red%22%7D,%0A%20%20media(%7B%7D,%20%7B%0A%20%20%20%20color:%20%22green%22%0A%20%20%7D),%0A%20%20media(%7BminWidth:%20800%7D,%20%7B%0A%20%20%20%20color:%20%22yellow%22%20//not%20working%0A%20%20%7D),%0A%20%20media(%7BminWidth:%201200%7D,%20%7B%0A%20%20%20%20color:%20%22blue%22%20//not%20working%0A%20%20%7D)%0A);%0A%0Aconst%20b%20=%20style(%0A%20%20%7Bcolor:%20%22grey%22%7D,%0A%20%20media(%7B%7D,%20%7B%0A%20%20%20%20color:%20%22orange%22%0A%20%20%7D)%0A);%0A%0A%3Cdiv%3E%0A%20%20%3Cdiv%20className=%7Ba%7D%3ETEST%201%3C/div%3E%0A%20%20%3Cdiv%20className=%7Bb%7D%3ETEST%202%3C/div%3E%0A%3C/div%3E

**Comment by basarat** [comment]
Please write the media queries as distinct sets. This is covered here : http://typestyle.io/#/advanced/concept-ordering-media-queries 

Fixed sample : http://typestyle.io/play/#src=const%20a%20=%20style(%0A%20%20media(%7BmaxWidth:790%7D,%20%7B%0A%20%20%20%20color:%20%22green%22%0A%20%20%7D),%0A%20%20media(%7BminWidth:%20800,%20maxWidth:%201199%7D,%20%7B%0A%20%20%20%20color:%20%22yellow%22%0A%20%20%7D),%0A%20%20media(%7BminWidth:%201200%7D,%20%7B%0A%20%20%20%20color:%20%22blue%22%0A%20%20%7D)%0A);%0A%0Aconst%20b%20=%20style(%0A%20%20%7Bcolor:%20%22grey%22%7D,%0A%20%20media(%7B%7D,%20%7B%0A%20%20%20%20color:%20%22orange%22%0A%20%20%7D)%0A);%0A%0A%3Cdiv%3E%0A%20%20%3Cdiv%20className=%7Ba%7D%3ETEST%201%3C/div%3E%0A%20%20%3Cdiv%20className=%7Bb%7D%3ETEST%202%3C/div%3E%0A%3C/div%3E

Artifact of deduping :rose:

**Comment by mzygmunt** [comment]
@basarat thanks for reply but it doesn't solve my problem. I need to make a universal, responsive grid for my UI framework. I want to use several breakpoints to determine the width of the columns (like Bootstrap). In this case, I can't set maxwidth, because I would have to define all the breakpoints for all columns every time.

I can see that, currently classes are not sorted before returning to HTML and this causes a problem. I think the solution is to add sorting result as follows:

1. Classes - always top of <script>
2. Media - always bottom of <script>
3. Media sorted: type (asc) maxwidth (desc) minwidth (desc)

Example result:
```css
.a {}
@media (){}
@media (max-width: 500px){}
@media (max-width: 400px){}
@media (min-width: 1200px){}
@media (min-width: 600px){}
@media (min-width: 400px and max-width: 500px){}
@media (min-width: 400px and max-width: 200px){}
@media (min-width: 200px and max-width: 500px){}
```

I think it would solve the problem comprehensively. What do you think about it?

**Comment by notoriousb1t** [comment]
I don't think sorting globally to fix this problem is the best approach.  Maybe sorting per hashed class might make sense.

So the output of your code is 

```css
.f83dnfs{color:red}
@media (min-width: 800px){
  .f83dnfs{color:yellow}
}
@media (min-width: 1200px){
  .f83dnfs{color:blue}
}
.f1te75fc{color:grey}
@media{.f83dnfs{color:green}
.f1te75fc{color:orange}
```

I'm curious if the order change is due to typestyle merging the objects or if this is something we should raise with free-style.

**Comment by mzygmunt** [comment]
@notoriousb1t why is this not a good idea? In most cases, the media clausules used to override classes, so they must be at the end of the result css. In addition, the media overwrite media at specific breakpoints, therefore they must be properly sorted after merged. The rest can be solved by a combination of !important.
In your example 1200px breakpoint will override 800px and clear @media will override rest, so this is not good solution.

**Comment by notoriousb1t** [comment]
@mzygmunt  Sorting globally would require typestyle to become really opinionated about how CSS is written.  The responsibility of how all rules are ordered would be in typestyle's hands.  I think it could get really complicated and hard to explain when accounting for all types of rules/atrules in CSS.  

The other issue with reordering globally is that there is a possibility two $nest selectors with the same specificity on a parent and a child could interfere with one another.

```!important``` is a duct tape, a paperclip, and a rubberband.  I don't think we should introduce something to typestyle that would require its use.

**It is a good thought and a good idea**, but would introduce complexity that shouldn't be in typestyle.

@basarat's solution should work, but that it might be good to revisit if there is a way to respect the order that styles are specified while still doing the hashing.

**If the best answer is to do sorting**, I think it should be done at the hashed class level, not globally across all styles.

**Comment by mzygmunt** [comment]
@notoriousb1t If we do it at the hashed class level, the specified media breakpoints can't be merged with other media breakpoints with the same parameters like min/maxWidth but owned by other classes. It makes sense. In addition, we can add a parameter to the style function, indicating whether sort media or merge them with others (like now).

**Comment by basarat** [comment]
> I'm curious if the order change is due to typestyle merging the objects or if this is something we should raise with free-style.

Due to free-style and caught me off guard once as well : https://github.com/blakeembrey/free-style/issues/41 (and I analysed it poorly them ... ashamed 😳). Hence the documentation and guidance at http://typestyle.io/#/advanced/concept-ordering-media-queries showing making distinct sets and a `media` function to help writing such code easier. 


> I need to make a universal, responsive grid for my UI framework. I want to use several breakpoints to determine the width of the columns (like Bootstrap).

If you show me the code I am sure it can be written as distinct sets. I don't see a mathematical limitation here. 

As a TIP I have the following in my code base: 

```ts
/**
 * Responsive Containers
 */
interface ResponsiveMarginedProps extends PrimitiveProps {
  margin?: number;
  breakpoint?: number;
}

interface ResponsiveGridParentProps extends PrimitiveProps {
  margin?: number;
  breakpoint?: number;
}
export const ResponsiveGridParent = (props: ResponsiveGridParentProps) => {
  const {margin, breakpoint, ...otherProps} = props;

  const spacing = (margin == null ? defaultValues.spacing : margin);
  const breakpointNum = (breakpoint || defaultValues.breakpoints.phone)
  const breakpointPx = (num) => num + 'px';

  const children = React.Children.toArray(props.children).filter(c => !!c);

  const parentClassName = typestyle.classes(
    props.className,
    typestyle.style(
      csstips.layerParent,
      /** Lower than breakpoint: Vertical Margined */
      typestyle.media({ minWidth: 0, maxWidth: breakpointNum }, csstips.verticallySpaced(spacing)),
      /** Bigger than breakpoint: Horizontal Margined */
      typestyle.media({ minWidth: breakpointNum + 1 }, csstips.horizontallySpaced(spacing)),
    )
  );

  const childClassName = (className) => typestyle.classes(
    className,
    typestyle.style(
      csstips.inlineBlock,
      /** Lower than breakpoint: full sized */
      typestyle.media({ minWidth: 0, maxWidth: breakpointNum }, { width: '100%' }),
      /** Bigger than breakpoint: percent sized */
      typestyle.media({ minWidth: breakpointNum + 1 }, { width: `calc(${(1 / children.length) * 100}% - ${spacing - spacing / children.length}px)` }),
    )
  );

  return (
    <div {...otherProps} className={parentClassName} data-comment="ResponsiveGridParent">
      {
        children.map((child, i) => <div data-comment="ResponsiveGridChild" key={(child as any).key || i} className={childClassName((child as any).className)}>{child}</div>)
      }
    </div>
  );
}
ResponsiveGridParent.displayName = "ResponsiveGridParent";
```

It just splits the space equally between its children with fixed `px` sized margins. Wrote that purely for the work project business requirements. I can customize this function in a 100 ways to make it px sized margins / distribution ratios etc (but haven't as a business requirement hasn't come up) :rose:

**Comment by mzygmunt** [comment]
Here is my simplified code of row/col components:
```typescript
interface IColProps {
    width?: {
        sm?: string | number;
        md?: string | number;
        lg?: string | number;
    };
}

const breakpoints: any = {
    sm: 0,
    md: 700,
    lg: 1200
};

export class Row extends React.Component<{}, {}> {
    public render(): React.ReactElement<{}> {
        const rowStyle: string = style({
            width: "100%",
            display: "flex",
            flexDirection: "col"
        });

        return (
            <div className={rowStyle} data-comment="row">
                {this.props.children}
            </div>
        );
    }
}
export class Col extends React.Component<IColProps, {}> {
    public static defaultProps: IColProps = {
        width: {}
    };
    public render(): React.ReactElement<{}> {
        const widthStyle: string = style(
            { $debugName: "width" },
            media({}, { width: this.props.width.sm || "100%" }),
            this.props.width.md && media({ minWidth: breakpoints.md },
                { width: this.props.width.md }
            ),
            this.props.width.lg && media({ minWidth: breakpoints.lg },
                { width: this.props.width.lg }
            )
        );

        return (
            <div className={widthStyle} data-comment="col">
                {this.props.children}
            </div>
        );
    }
}
```
And here is an example of using:
```typestyle
<div>
    <Row>
        <Col width={{ sm: "20%", md: "60%" }}>
            Test 1
        </Col>
        <Col width={{ sm: "80%", md: "40%" }}>
            Test 2
        </Col>
    </Row>
    <Row>
        <Col width={{ sm: "10%" }}>
            Test 3
        </Col>
        <Col width={{ sm: "10%" }}>
            Test 4
        </Col>
    </Row>
</div>
```

Note that the md breakpoints doesn't work in this case.

**Comment by basarat** [comment]
[playground url](http://typestyle.io/play/#src=interface%20IColProps%20%7B%0A%20%20%20%20width?:%20%7B%0A%20%20%20%20%20%20%20%20sm?:%20string%20%7C%20number;%0A%20%20%20%20%20%20%20%20md?:%20string%20%7C%20number;%0A%20%20%20%20%20%20%20%20lg?:%20string%20%7C%20number;%0A%20%20%20%20%7D;%0A%7D%0A%0Aconst%20breakpoints:%20any%20=%20%7B%0A%20%20%20%20sm:%200,%0A%20%20%20%20md:%20700,%0A%20%20%20%20lg:%201200%0A%7D;%0A%0Aclass%20Row%20extends%20React.Component%3C%7B%7D,%20%7B%7D%3E%20%7B%0A%20%20%20%20public%20render():%20React.ReactElement%3C%7B%7D%3E%20%7B%0A%20%20%20%20%20%20%20%20const%20rowStyle:%20string%20=%20style(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20width:%20%22100%25%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20display:%20%22flex%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20flexDirection:%20%22column%22%0A%20%20%20%20%20%20%20%20%7D);%0A%0A%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20className=%7BrowStyle%7D%20data-comment=%22row%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bthis.props.children%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C/div%3E%0A%20%20%20%20%20%20%20%20);%0A%20%20%20%20%7D%0A%7D%0Aclass%20Col%20extends%20React.Component%3CIColProps,%20%7B%7D%3E%20%7B%0A%20%20%20%20public%20static%20defaultProps:%20IColProps%20=%20%7B%0A%20%20%20%20%20%20%20%20width:%20%7B%7D%0A%20%20%20%20%7D;%0A%20%20%20%20public%20render():%20React.ReactElement%3C%7B%7D%3E%20%7B%0A%20%20%20%20%20%20%20const%20widthStyle:%20string%20=%20style(%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20$debugName:%20%22width%22%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20media(%7B%7D,%20%7B%20width:%20this.props.width.sm%20%7C%7C%20%22100%25%22%20%7D),%0A%20%20%20%20%20%20%20%20%20%20%20%20this.props.width.md%20&&%20media(%7B%20minWidth:%20breakpoints.md%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20width:%20this.props.width.md%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20),%0A%20%20%20%20%20%20%20%20%20%20%20%20this.props.width.lg%20&&%20media(%7B%20minWidth:%20breakpoints.lg%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20width:%20this.props.width.lg%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20)%0A%20%20%20%20%20%20%20%20);%0A%0A%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20className=%7BwidthStyle%7D%20data-comment=%22col%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bthis.props.children%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C/div%3E%0A%20%20%20%20%20%20%20%20);%0A%20%20%20%20%7D%0A%7D%0A%0A%3Cdiv%3E%0A%20%20%20%20%3CRow%3E%0A%20%20%20%20%20%20%20%20%3CCol%20width=%7B%7B%20sm:%20%2220%25%22,%20md:%20%2260%25%22%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20Test%201%0A%20%20%20%20%20%20%20%20%3C/Col%3E%0A%20%20%20%20%20%20%20%20%3CCol%20width=%7B%7B%20sm:%20%2280%25%22,%20md:%20%2240%25%22%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20Test%202%0A%20%20%20%20%20%20%20%20%3C/Col%3E%0A%20%20%20%20%3C/Row%3E%0A%20%20%20%20%3CRow%3E%0A%20%20%20%20%20%20%20%20%3CCol%20width=%7B%7B%20sm:%20%2210%25%22%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20Test%203%0A%20%20%20%20%20%20%20%20%3C/Col%3E%0A%20%20%20%20%20%20%20%20%3CCol%20width=%7B%7B%20sm:%20%2210%25%22%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20Test%204%0A%20%20%20%20%20%20%20%20%3C/Col%3E%0A%20%20%20%20%3C/Row%3E%0A%3C/div%3E)

**Comment by basarat** [comment]
Percent width media query breakpoints don't make sense. The code is wrong :-/

**Comment by basarat** [comment]
Sorry ... analyzing still

**Comment by basarat** [comment]
[Fixed sample](http://typestyle.io/play/#src=interface%20IColProps%20%7B%0A%20%20%20%20width?:%20%7B%0A%20%20%20%20%20%20%20%20sm?:%20string%20%7C%20number;%0A%20%20%20%20%20%20%20%20md?:%20string%20%7C%20number;%0A%20%20%20%20%20%20%20%20lg?:%20string%20%7C%20number;%0A%20%20%20%20%7D;%0A%7D%0A%0Aconst%20breakpoints:%20any%20=%20%7B%0A%20%20%20%20sm:%200,%0A%20%20%20%20md:%20700,%0A%20%20%20%20lg:%201200%0A%7D;%0A%0Aclass%20Row%20extends%20React.Component%3C%7B%7D,%20%7B%7D%3E%20%7B%0A%20%20public%20render():%20React.ReactElement%3C%7B%7D%3E%20%7B%0A%20%20%20%20const%20rowStyle:%20string%20=%20style(%7B%0A%20%20%20%20%20%20%20%20width:%20%22100%25%22,%0A%20%20%20%20%7D);%0A%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cdiv%20className=%7BrowStyle%7D%20data-comment=%22row%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%7Bthis.props.children%7D%0A%20%20%20%20%20%20%20%20%3C/div%3E%0A%20%20%20%20);%0A%20%20%7D%0A%7D%0Aclass%20Col%20extends%20React.Component%3CIColProps,%20%7B%7D%3E%20%7B%0A%20%20public%20static%20defaultProps:%20IColProps%20=%20%7B%0A%20%20%20%20%20%20width:%20%7B%7D%0A%20%20%7D;%0A%20%20public%20render():%20React.ReactElement%3C%7B%7D%3E%20%7B%0A%20%20%20%20const%20width%20=%20this.props.width;%0A%20%20%20%20%0A%20%20%20%20const%20widthStyle:%20string%20=%20style(%0A%20%20%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20$debugName:%20%22width%22,%0A%20%20%20%20%20%20%20%20%20%20display:%20'inline-block'%0A%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20media(width.md%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20?%20%7BmaxWidth:%20breakpoints.md%20-%201%7D%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20:%20width.lg%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20?%20%7BmaxWidth:%20breakpoints.lg%20-%201%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20:%20%7B%7D,%20%7B%20width:%20width.sm%20%7C%7C%20%22100%25%22%20%7D),%0A%20%20%20%20%20%20%20%20width.md%20&&%20media(%7B%20minWidth:%20breakpoints.md%20,%20...(%0A%20%20%20%20%20%20%20%20%20%20width.lg%20?%20%7BmaxWidth:%20breakpoints.lg%20-%201%7D%20:%20%7B%7D%0A%20%20%20%20%20%20%20%20)%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20width:%20width.md%20%7D%0A%20%20%20%20%20%20%20%20),%0A%20%20%20%20%20%20%20%20width.lg%20&&%20media(%7B%20minWidth:%20breakpoints.lg%20%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20width:%20width.lg%20%7D%0A%20%20%20%20%20%20%20%20)%0A%20%20%20%20);%0A%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cdiv%20className=%7BwidthStyle%7D%20data-comment=%22col%22%20children=%7Bthis.props.children%7D%20/%3E%0A%20%20%20%20);%0A%20%20%7D%0A%7D%0A%0A%3Cdiv%3E%0A%20%20%20%20%3CRow%3E%0A%20%20%20%20%20%20%20%20%3CCol%20width=%7B%7B%20sm:%20%2220%25%22,%20md:%20%2260%25%22%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20Test%201%0A%20%20%20%20%20%20%20%20%3C/Col%3E%0A%20%20%20%20%20%20%20%20%3CCol%20width=%7B%7B%20sm:%20%2280%25%22,%20md:%20%2240%25%22%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20Test%202%0A%20%20%20%20%20%20%20%20%3C/Col%3E%0A%20%20%20%20%3C/Row%3E%0A%20%20%20%20%3CRow%3E%0A%20%20%20%20%20%20%20%20%3CCol%20width=%7B%7B%20sm:%20%2210%25%22%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20Test%203%0A%20%20%20%20%20%20%20%20%3C/Col%3E%0A%20%20%20%20%20%20%20%20%3CCol%20width=%7B%7B%20sm:%20%2210%25%22%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20Test%204%0A%20%20%20%20%20%20%20%20%3C/Col%3E%0A%20%20%20%20%3C/Row%3E%0A%3C/div%3E)

Hope that helps :rose:

**Comment by mzygmunt** [comment]
@basarat, thank you for your time. After a small modification it works great 🌹
